import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    // 1. Start Here
    'intro',
    // 2. How Scrimba Works
    {
      type: 'category',
      label: 'How Scrimba Works',
      items: [
        'how-it-works/how-scrims-work',
        'how-it-works/using-scrimba',
        'how-it-works/is-scrimba-free',
        'how-it-works/accreditation',
        'how-it-works/certificates',
        'how-it-works/learning-speed',
        'how-it-works/tutorial-hell',
      ],
    },
    // 3. Who It's For (orientation / self-select, with hub landing page)
    {
      type: 'category',
      label: "Who It's For",
      link: { type: 'doc', id: 'for/index' },
      items: [
        'for/beginners',
        'for/cs-students',
        'for/designers',
        'for/marketers',
        'for/busy-professionals',
      ],
    },
    // 4. Learning Paths
    {
      type: 'category',
      label: 'Learning Paths',
      link: { type: 'doc', id: 'paths/index' },
      items: [
        'paths/frontend-developer-path',
        'paths/fullstack-developer-path',
        'paths/backend-developer-path',
        'paths/ai-engineer-path',
        'paths/study-plan',
      ],
    },
    // 5. Courses by Topic
    {
      type: 'category',
      label: 'Courses by Topic',
      link: { type: 'doc', id: 'courses/index' },
      items: [
        {
          type: 'category',
          label: 'React',
          link: { type: 'doc', id: 'courses/react/index' },
          items: [{ type: 'autogenerated', dirName: 'courses/react' }],
        },
        {
          type: 'category',
          label: 'JavaScript',
          link: { type: 'doc', id: 'courses/javascript/index' },
          items: [{ type: 'autogenerated', dirName: 'courses/javascript' }],
        },
        {
          type: 'category',
          label: 'CSS & Design',
          link: { type: 'doc', id: 'courses/css/index' },
          items: [{ type: 'autogenerated', dirName: 'courses/css' }],
        },
        {
          type: 'category',
          label: 'AI & Machine Learning',
          link: { type: 'doc', id: 'courses/ai/index' },
          items: [{ type: 'autogenerated', dirName: 'courses/ai' }],
        },
        {
          type: 'category',
          label: 'Backend & Databases',
          link: { type: 'doc', id: 'courses/backend/index' },
          items: [{ type: 'autogenerated', dirName: 'courses/backend' }],
        },
        {
          type: 'category',
          label: 'Python',
          link: { type: 'doc', id: 'courses/python/index' },
          items: [{ type: 'autogenerated', dirName: 'courses/python' }],
        },
        {
          type: 'category',
          label: 'TypeScript',
          link: { type: 'doc', id: 'courses/typescript/index' },
          items: [{ type: 'autogenerated', dirName: 'courses/typescript' }],
        },
      ],
    },
    // 6. Practice (with hub landing page)
    {
      type: 'category',
      label: 'Practice',
      link: { type: 'doc', id: 'practice/index' },
      items: [
        'practice/practice-css-grid',
        'practice/practice-flexbox',
        'practice/practice-tailwind-css',
        'practice/practice-javascript-arrays',
        'practice/practice-api-calls',
        'practice/practice-react-hooks',
        'practice/practice-typescript',
        'practice/practice-ai-engineering',
        'practice/practice-react-projects',
        'practice/react-portfolio-project-ideas',
        'practice/build-a-weather-app-interactively',
      ],
    },
    // 7. Free Roadmaps (React + Next.js; leaf concept pages consolidated into
    // each index on 2026-05-29, so each roadmap is now a single hub page)
    {
      type: 'category',
      label: 'Free Roadmaps',
      items: [
        'learn-react/index',
        'learn-nextjs/index',
      ],
    },
    // 8. Scrimba vs Alternatives (decision stage)
    {
      type: 'category',
      label: 'Scrimba vs Alternatives',
      link: { type: 'doc', id: 'comparisons/index' },
      items: [
        'comparisons/scrimba-vs-codecademy',
        'comparisons/scrimba-vs-udemy',
        'comparisons/scrimba-vs-freecodecamp',
        'comparisons/scrimba-vs-coursera',
        'comparisons/scrimba-vs-odin-project',
        'comparisons/scrimba-vs-youtube',
        'comparisons/scrimba-vs-frontendmasters',
        'comparisons/scrimba-vs-boot-dev',
        'comparisons/scrimba-vs-treehouse',
        'comparisons/scrimba-vs-zerotomastery',
        'comparisons/scrimba-vs-pluralsight',
        'comparisons/scrimba-vs-educative',
        'comparisons/scrimba-vs-fireship',
      ],
    },
    // 9. Pricing (commitment stage)
    {
      type: 'category',
      label: 'Pricing',
      link: { type: 'doc', id: 'pricing/index' },
      items: [
        'pricing/pro-vs-free',
        'pricing/scrimba-free-trial',
        'pricing/student-discount',
        'pricing/refund-policy',
        'pricing/scrimba-vs-bootcamps',
      ],
    },
    // 10. Help & Support
    {
      type: 'category',
      label: 'Help & Support',
      items: [
        'help/billing',
        'help/troubleshooting',
        'help/community-and-events',
      ],
    },
    // 11. FAQ (curated hub linking to the distributed answers)
    'faq/index',
    // 12. Updates
    {
      type: 'category',
      label: 'Updates',
      items: ['changelog'],
    },
  ],
};

export default sidebars;
