import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Scrimba Pricing',
      link: {type: 'doc', id: 'pricing/index'},
      items: [
        'pricing/pro-vs-free',
        'pricing/student-discount',
        'pricing/refund-policy',
        'pricing/scrimba-vs-bootcamps',
      ],
    },
    {
      type: 'category',
      label: 'Learning Paths',
      link: {type: 'doc', id: 'paths/index'},
      items: [
        'paths/frontend-developer-path',
        'paths/fullstack-developer-path',
        'paths/backend-developer-path',
        'paths/ai-engineer-path',
        'paths/study-plan',
      ],
    },
    {
      type: 'category',
      label: 'Courses by Topic',
      link: {type: 'doc', id: 'courses/index'},
      items: [
        {
          type: 'category',
          label: 'React',
          link: {type: 'doc', id: 'courses/react/index'},
          items: [{type: 'autogenerated', dirName: 'courses/react'}],
        },
        {
          type: 'category',
          label: 'JavaScript',
          link: {type: 'doc', id: 'courses/javascript/index'},
          items: [{type: 'autogenerated', dirName: 'courses/javascript'}],
        },
        {
          type: 'category',
          label: 'AI & Machine Learning',
          link: {type: 'doc', id: 'courses/ai/index'},
          items: [{type: 'autogenerated', dirName: 'courses/ai'}],
        },
        {
          type: 'category',
          label: 'CSS & Design',
          link: {type: 'doc', id: 'courses/css/index'},
          items: [{type: 'autogenerated', dirName: 'courses/css'}],
        },
        {
          type: 'category',
          label: 'Backend & Databases',
          link: {type: 'doc', id: 'courses/backend/index'},
          items: [{type: 'autogenerated', dirName: 'courses/backend'}],
        },
        {
          type: 'category',
          label: 'Python',
          link: {type: 'doc', id: 'courses/python/index'},
          items: [{type: 'autogenerated', dirName: 'courses/python'}],
        },
        {
          type: 'category',
          label: 'TypeScript',
          link: {type: 'doc', id: 'courses/typescript/index'},
          items: [{type: 'autogenerated', dirName: 'courses/typescript'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Scrimba vs Alternatives',
      items: [
        'comparisons/scrimba-vs-codecademy',
        'comparisons/scrimba-vs-udemy',
        'comparisons/scrimba-vs-freecodecamp',
        'comparisons/scrimba-vs-frontendmasters',
        'comparisons/scrimba-vs-treehouse',
        'comparisons/scrimba-vs-odin-project',
        'comparisons/scrimba-vs-coursera',
      ],
    },
    {
      type: 'category',
      label: 'FAQ & Help',
      link: {type: 'doc', id: 'faq/index'},
      items: [
        'faq/billing',
        'faq/certificates',
        'faq/discord-community',
        'faq/community-and-events',
        'faq/platform-issues',
      ],
    },
  ],
};

export default sidebars;
