/**
 * Client module to fix accessibility issues in Docusaurus-generated markup.
 *
 * 1. Blog post TOC sidebar: wraps .col--2 content in a <nav> landmark
 * 2. Blog list page: injects a visually-hidden <h1> inside <main>
 * 3. Scrollable tables: adds tabindex/role for keyboard access (docs + blog)
 * 4. Task-list checkboxes: adds aria-label from text content
 * 5. Empty table headers: fills with '#' and adds scope
 * 6. Search page: injects <main> landmark
 */
import type { ClientModule } from '@docusaurus/types';

function fixBlogTocLandmark() {
  if (!document.querySelector('.blog-post-page')) return;

  const toc = document.querySelector<HTMLElement>('.col.col--2');
  if (!toc || toc.closest('nav')) return;

  const nav = document.createElement('nav');
  nav.setAttribute('aria-label', 'Table of contents');

  while (toc.firstChild) {
    nav.appendChild(toc.firstChild);
  }
  toc.appendChild(nav);
}

function fixBlogListHeading() {
  if (!document.querySelector('.blog-list-page')) return;

  const main = document.querySelector('main');
  if (!main || main.querySelector('h1')) return;

  const h1 = document.createElement('h1');
  h1.className = 'sr-only';
  h1.textContent = 'ScrimbaGuide Blog';
  main.prepend(h1);
}

function fixScrollableTables() {
  // Target all tables: docs, blog posts, and comparison tables
  let tableIndex = 0;
  document.querySelectorAll<HTMLElement>(
    '.theme-doc-markdown table, .comparison-table, article table, .blog-wrapper table, .markdown table'
  ).forEach((table) => {
    if (table.hasAttribute('tabindex')) return;
    // Check if table or its wrapper is scrollable
    const wrapper = table.parentElement;
    const isScrollable =
      table.scrollWidth > table.clientWidth ||
      (wrapper && wrapper.scrollWidth > wrapper.clientWidth);
    if (isScrollable) {
      tableIndex++;
      table.setAttribute('tabindex', '0');
      table.setAttribute('role', 'region');
      // Use unique aria-labels to prevent landmark-unique violations
      table.setAttribute('aria-label', `Data table ${tableIndex}`);
    }
  });
}

function fixTaskListCheckboxes() {
  document.querySelectorAll<HTMLInputElement>(
    '.task-list-item > input[type="checkbox"]'
  ).forEach((checkbox) => {
    if (checkbox.getAttribute('aria-label')) return;
    const parent = checkbox.closest('.task-list-item');
    const text = parent?.textContent?.trim() || 'Task item';
    checkbox.setAttribute('aria-label', text);
  });
}

function fixEmptyTableHeaders() {
  document.querySelectorAll('th').forEach((th) => {
    if (!th.textContent?.trim()) {
      th.textContent = '#';
    }
    if (!th.hasAttribute('scope')) {
      th.setAttribute('scope', 'col');
    }
  });
}

function fixSearchPageLandmark() {
  // /search page generated by search plugin lacks a <main> landmark
  if (!window.location.pathname.includes('/search')) return;
  if (document.querySelector('main')) return;

  const content = document.querySelector<HTMLElement>('#__docusaurus_skipToContent_fallback');
  if (!content) return;

  const main = document.createElement('main');
  main.setAttribute('role', 'main');

  // Move all children into main
  while (content.firstChild) {
    main.appendChild(content.firstChild);
  }
  content.appendChild(main);
}

const module: ClientModule = {
  onRouteDidUpdate() {
    setTimeout(() => {
      fixBlogTocLandmark();
      fixBlogListHeading();
      fixScrollableTables();
      fixTaskListCheckboxes();
      fixEmptyTableHeaders();
      fixSearchPageLandmark();
    }, 100);
  },
};

export default module;
