/**
 * The global-chrome closure invariant (I18N-PLAN.md section 4 Phase 2 task (b)).
 *
 * Navbar, footer and MegaMenu link to a fixed set of routes on EVERY page. Under
 * `onBrokenLinks: 'throw'`, a locale whose route set omits any one of them cannot
 * build at all: the failure is not a missing page, it is a hard build error in
 * that locale, and it surfaces only once someone tries to ship it.
 *
 * When this test fails, THE FIX IS TO EXPAND THE ROUTE SET, never to rewrite
 * links per locale. Locale-conditional chrome links would fork the navigation
 * between markets and quietly break path parity.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSourceUniverse, resolveRouteSet, loadRoster } from '../build-coverage-manifest.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const tiers = JSON.parse(fs.readFileSync(path.join(ROOT, 'i18n', 'tiers.json'), 'utf8'));
const universe = buildSourceUniverse();

/** Normalize a `to:` target the way Docusaurus resolves it: trailing slash, no hash. */
const routeOf = (to) => {
  const clean = to.split('#')[0].split('?')[0];
  if (!clean.startsWith('/')) return null;
  return clean === '/' ? '/' : `/${clean.replace(/^\/+|\/+$/g, '')}/`;
};

/**
 * Every internal route reachable from global chrome, read from the real config
 * and component source rather than restated here. A hardcoded copy would drift
 * the moment someone adds a navbar item, which is exactly the case this guards.
 */
function chromeRoutes() {
  const found = new Set();
  const sources = [
    path.join(ROOT, 'config', 'navigation.ts'),
    path.join(ROOT, 'src', 'components', 'MegaMenu.tsx'),
  ];
  for (const file of sources) {
    if (!fs.existsSync(file)) continue;
    const src = fs.readFileSync(file, 'utf8');
    for (const m of src.matchAll(/\bto:\s*'(\/[^']*)'/g)) {
      const r = routeOf(m[1]);
      if (r) found.add(r);
    }
  }
  return found;
}

const LEGAL_PREFIX = '/legal/';

test('chrome routes are discovered from real config, not assumed', () => {
  const routes = chromeRoutes();
  assert.ok(routes.size >= 10, `expected to discover the chrome link set, got ${routes.size}`);
  // Spot-check the ones the plan calls out by name, so a parsing regression that
  // silently finds "some" routes still fails.
  for (const r of ['/docs/paths/', '/docs/courses/', '/docs/comparisons/', '/docs/pricing/', '/blog/']) {
    assert.ok(routes.has(r), `chrome route ${r} was not discovered`);
  }
});

test('every chrome route exists as a real English route', () => {
  const real = new Set(universe.map((e) => e.route));
  // Routes with no markdown source are still real routes: /blog/ is generated by
  // plugin-content-blog, and the alwaysBuilt entries are .tsx pages translated
  // through code.json rather than a translated markdown file.
  const generated = new Set(['/blog/', ...(tiers.alwaysBuilt?.routes ?? [])]);
  const missing = [...chromeRoutes()].filter(
    (r) => !real.has(r) && !generated.has(r) && !r.startsWith(LEGAL_PREFIX),
  );
  assert.deepEqual(missing, [], `chrome links point at nonexistent routes: ${missing.join(', ')}`);
});

for (const setName of ['core', 'micro']) {
  test(`route set '${setName}' satisfies the global-chrome closure invariant`, () => {
    const declared = resolveRouteSet(setName, tiers, universe);
    const alwaysBuilt = new Set(tiers.alwaysBuilt?.routes ?? []);

    const missing = [...chromeRoutes()].filter((r) => {
      // Legal pages are English-only in every locale by decision (section 1) and
      // are replaced by a localized notice line, so they are exempt here. That
      // exemption is only safe because the footer must ALSO drop those links in
      // non-en locales; see the section 4 Phase 2 task (d) note below.
      if (r.startsWith(LEGAL_PREFIX)) return false;
      if (alwaysBuilt.has(r)) return false;
      // The blog list route is generated by plugin-content-blog whenever the
      // locale has any blog content at all.
      if (r === '/blog/') return false;
      return !declared.has(r);
    });

    assert.deepEqual(
      missing,
      [],
      `Route set '${setName}' omits chrome-reachable routes: ${missing.join(', ')}\n` +
      `FIX: add them to routeSets.${setName} in i18n/tiers.json. Do NOT make the ` +
      `navbar/footer locale-conditional.`,
    );
  });
}

test('micro is a strict subset of core', () => {
  const core = resolveRouteSet('core', tiers, universe);
  const micro = resolveRouteSet('micro', tiers, universe);
  const extra = [...micro].filter((r) => !core.has(r));
  assert.deepEqual(extra, [], `micro contains routes absent from core: ${extra.join(', ')}`);
  assert.ok(micro.size < core.size, 'micro must be strictly smaller than core');
});

test('every declared route in every route set has an English source', () => {
  const real = new Set(universe.map((e) => e.route));
  for (const setName of Object.keys(tiers.routeSets)) {
    const declared = resolveRouteSet(setName, tiers, universe);
    const orphans = [...declared].filter((r) => !real.has(r));
    assert.deepEqual(
      orphans,
      [],
      `Route set '${setName}' declares routes with no English source: ${orphans.join(', ')}`,
    );
  }
});

test('Tier B retains every category hub and drops every course leaf', () => {
  const set = resolveRouteSet('full-minus-course-leaves', tiers, universe);
  const hubs = [...set].filter((r) => /^\/docs\/courses\/[^/]+\/$/.test(r));
  const leaves = [...set].filter((r) => /^\/docs\/courses\/[^/]+\/.+\/$/.test(r));
  assert.equal(leaves.length, 0, `Tier B must drop all course leaves, kept: ${leaves.join(', ')}`);
  assert.equal(hubs.length, 7, `Tier B must retain all 7 category hubs, kept ${hubs.length}`);
});

test('legal pages are excluded from every locale', () => {
  const globs = tiers.alwaysExcluded?.globs ?? [];
  assert.ok(globs.includes('legal/**'), 'legal/** must be in alwaysExcluded');
  for (const setName of Object.keys(tiers.routeSets)) {
    const declared = resolveRouteSet(setName, tiers, universe);
    const legal = [...declared].filter((r) => r.startsWith(LEGAL_PREFIX));
    assert.deepEqual(legal, [], `Route set '${setName}' declares legal routes: ${legal.join(', ')}`);
  }
});
